// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHLbFJ2KpcCYwp-d7mKipSvNOoti6f4QI',
    appId: '1:281646115646:web:1d3ac08ea454b87ee0da6f',
    messagingSenderId: '281646115646',
    projectId: 'easy-vahan-2d70a',
    authDomain: 'easy-vahan-2d70a.firebaseapp.com',
    storageBucket: 'easy-vahan-2d70a.appspot.com',
    measurementId: 'G-V1WB0H0GST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6fbcRaOciRs5QBh5AGhOyCKig4RWB9Kg',
    appId: '1:281646115646:android:f5ca4752e4844ef8e0da6f',
    messagingSenderId: '281646115646',
    projectId: 'easy-vahan-2d70a',
    storageBucket: 'easy-vahan-2d70a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('GOOGLE_MAPS_API_KEY'),
    appId: '1:281646115646:ios:2d5c74ebdf7aa58ae0da6f',
    messagingSenderId: '281646115646',
    projectId: 'easy-vahan-2d70a',
    storageBucket: 'easy-vahan-2d70a.appspot.com',
    iosBundleId: 'com.example.easyVahan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('GOOGLE_MAPS_API_KEY'),
    appId: '1:281646115646:ios:e57f5f2b5ac2a61ae0da6f',
    messagingSenderId: '281646115646',
    projectId: 'easy-vahan-2d70a',
    storageBucket: 'easy-vahan-2d70a.appspot.com',
    iosBundleId: 'com.example.easyVahan.RunnerTests',
  );
}
